version: 2
workflows:
  version: 2
  test:
    jobs:
      - my-test

jobs:
  my-test:
    docker:
      - image: circleci/python:2.7-stretch
    working_directory: ~/my-foundation
    steps:
      - checkout
      - run:
          name: test app
          command: |
            echo "Hello Tests"
            echo "how are you"